# Generated by Django 5.1.3 on 2024-11-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='context',
            field=models.JSONField(default=dict),
        ),
    ]
