# Generated by Django 5.1.3 on 2025-02-15 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.CharField(max_length=50)),
                ('voice_name', models.CharField(max_length=100)),
                ('accent', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('stability', models.FloatField(default=0.5)),
                ('similarity_boost', models.FloatField(default=0.8)),
                ('style', models.FloatField(default=0.0)),
                ('use_speaker_boost', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
