# Generated by Django 5.1.3 on 2025-02-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_voiceconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceconfig',
            name='use_case',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
