# Generated by Django 5.1.3 on 2025-02-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_voiceconfig_use_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceconfig',
            name='emotional_expressiveness',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='formality_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='interaction_style',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='other_preferences',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='paraphrase_variability',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='persona_tone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='persona_traits',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='personalized_naming',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='preferred_reminder_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='progress_reporting',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='reminder_frequency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='reminder_tone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='response_length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voiceconfig',
            name='voice_feedback_style',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
