# Generated by Django 5.1.3 on 2025-02-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_assistant_id_user_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ttm_stage',
            field=models.CharField(blank=True, default='Precontemplation', help_text='TTM stage of the user.', max_length=50, null=True),
        ),
    ]
